#!/bin/bash
TOOLS=~/git/dcs-gradapps-prefilter/
SCHOOL="BISHOP'S|ATHABASCA|SENECA|RYERSON|ST MARY'S|XAVIER|MEMORIAL UNIV|LAKEHEAD|KINGSTON|GEORGE BROWN|CONCORDIA|WILFRID LAURIER|MANITOBA|GUELPH|UNIV OF VICTORIA|REGINA|WINDSOR"
. $TOOLS/uni.sh

