#!/bin/bash

TOOLS=~/git/dcs-gradapps-prefilter/

SCHOOL1='BERKELEY|HOPKINS|Stanford|STANFORD|BOSTON|GEORGIA|MIT|COLUMBIA UNIV|CORNELL|CALIFORNIA|WISCONSIN|CHAMPAIGN|MELLON|CINCINNATI|RUTGERS|SAN JOSE|TEXAS_AUSTIN|PENNSYLVANIA'

SCHOOL2='NEW YORK UNIV|Diablo Valley College|College of San Mateo|University of Michigan Ann Arbor|UNIV OF ROCHESTER|ST CLOUD STATE UNIV|PURDUE UNIV|HARVARD UNIV|DREXEL UNIV|COOPER UNION FOR THE ADVANCEMENT OF SCI|WELLESLEY COLL|University of Wyoming|UNIV OF UTAH|UNIV OF TULSA|UNIV OF TEXAS DALLAS|UNIV OF TEXAS AUSTIN|UNIV OF SOUTH FLORIDA|UNIV OF NORTH CAROLINA CHAPEL HILL|UNIV OF NEW MEXICO ALBUQUERQUE|UNIV OF MINNESOTA TWIN CITIES|UNIV OF MASSACHUSETTS AMHERST|UNIV OF CONNECTICUT (STORRS)|TEMPLE UNIV|SYRACUSE UNIV|SOUTH DAKOTA SCH OF MINES & TECH|RENSSELAER POLYT INST|PENNSYLVANIA STATE UNIV2|PASADENA CITY COLL|Pace Junior Science College|MIDLAND COLL|MICHIGAN STATE UNIV|METRO COLLEGE OF TECHNOLOGY|MASSACHUSETTS INST OF TECH|Iowa State University|INDIANA STATE UNIV|ILLINOIS INST OF TECH|GEORGE WASHINGTON UNIV|GEORGE MASON UNIV|DURHAM COLL OF A A & T|COLORADO SCH OF MINE|OHIO STATE UNIV|UNIV OF CHICAGO|UNIV OF WASHINGTON|SAN JOSE STATE UNIV|BEREA COLL'

SCHOOL=$SCHOOL2

echo
echo default filter $SCHOOL '(ostensibly)' finds the top Canadians unis
echo you can put this on command line or enter new one below
echo

if test ! -z "$1"
then
	SCHOOL="$1"
	echo $0 "filter by $SCHOOL"
else
	echo you can give another regexp on command line. or enter one below, if you enter nothing assumes above
	echo an example filter would be "$SCHOOL"
	read -p "enter school filter.. (just enter uses above default) > " school
	if test ! -z $school
	then
		SCHOOL="$school"
	fi
fi

DCS_STATUS=pf

set -x
python3 $TOOLS/eat.py --skip-prefilter "$SCHOOL"
