#!/bin/bash

TOOLS=~/git/dcs-gradapps-prefilter/

SCHOOL='BERKELEY|HOPKINS|Stanford|STANFORD|BOSTON|GEORGIA|MIT|COLUMBIA UNIV|CORNELL|CALIFORNIA|WISCONSIN|CHAMPAIGN|MELLON|CINCINNATI|RUTGERS|SAN JOSE|TEXAS_AUSTIN|PENNSYLVANIA|PURDUE'


. $TOOLS/uni.sh
