#!/bin/bash

TOOLS=~/git/dcs-gradapps-prefilter/

SCHOOL='NEW YORK UNIV|Diablo Valley College|College of San Mateo|University of Michigan Ann Arbor|UNIV OF ROCHESTER|ST CLOUD STATE UNIV|PURDUE UNIV|HARVARD UNIV|DREXEL UNIV|COOPER UNION FOR THE ADVANCEMENT OF SCI|WELLESLEY COLL|University of Wyoming|UNIV OF UTAH|UNIV OF TULSA|UNIV OF TEXAS DALLAS|UNIV OF TEXAS AUSTIN|UNIV OF SOUTH FLORIDA|UNIV OF NORTH CAROLINA CHAPEL HILL|UNIV OF NEW MEXICO ALBUQUERQUE|UNIV OF MINNESOTA TWIN CITIES|UNIV OF MASSACHUSETTS AMHERST|UNIV OF CONNECTICUT (STORRS)|TEMPLE UNIV|SYRACUSE UNIV|SOUTH DAKOTA SCH OF MINES & TECH|RENSSELAER POLYT INST|PENNSYLVANIA STATE UNIV2|PASADENA CITY COLL|Pace Junior Science College|MIDLAND COLL|MICHIGAN STATE UNIV|METRO COLLEGE OF TECHNOLOGY|MASSACHUSETTS INST OF TECH|Iowa State University|INDIANA STATE UNIV|ILLINOIS INST OF TECH|GEORGE WASHINGTON UNIV|GEORGE MASON UNIV|DURHAM COLL OF A A & T|COLORADO SCH OF MINE|OHIO STATE UNIV|UNIV OF CHICAGO|UNIV OF WASHINGTON|SAN JOSE STATE UNIV|BEREA COLL'

. $TOOLS/uni.sh
